CHOICE_COLOR = "cyan"
ERROR_COLOR  = "red"
SUCCES_COLOR = "green"
FRIENDLY_COLOR = "blue"
STANDARD_COLOR = "white"

PATH_SYMBOL = "⬧"
STARTING_SYMBOL = "S"
FINISHED_SYMBOL = "T"

PATH_COLOR = "green"
FINISHED_COLOR = "red"

MUSIC_DIR = "musics/"
DEFAULT_MUSIC = "pearls.ogg"